# Gradle
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m

# Kotlin Multiplatform
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.applyDefaultHierarchyTemplate=true
kotlin.native.cacheKind=none

# Compose
org.jetbrains.compose.experimental.uikit.enabled=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

# Misc
systemProp.org.gradle.internal.publish.checksums.insecure=true
