platform :ios, '15.0'

use_frameworks!

target 'iosApp' do
  pod 'composeApp', :path => '../composeApp'
  pod 'WebRTC-SDK', '125.6422.07'
end

post_install do |installer|
  java_home = '/Applications/Android Studio.app/Contents/jbr/Contents/Home'
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['JAVA_HOME'] = java_home
    end
  end
end
